#2장 팀과제 01번 - 1장 실습문제 1번 자동차 그리기 프로그램 수정하기
import turtle as t
t.shape("turtle")
#사용자에게 자동차크기, 색깔 입력 받기
size = int(input("자동차 크기는 얼마로 할까요? : "))
size_c = int(input("바퀴 크기는 얼마로 할까요? : "))
body_color = input("자동차 몸통 색깔은 어떤 색으로 할까요? : ")
top_color = input("자동차 상단 색깔은 어떤 색으로 할까요? : ")

# 몸통 그리기
t.up()
t.goto(-2 * size, -0.5 * size)
t.down()
t.fillcolor(body_color)
t.begin_fill()
t.forward(4 * size)
t.left(90)
t.forward(2 * size)
t.left(90)
t.forward(4 * size)
t.left(90)
t.forward(2 * size)
t.end_fill()

# 상단 그리기
t.up()
t.goto(-1 * size, 2.5 * size)
t.down()
t.fillcolor(top_color)
t.begin_fill()
t.forward(1 * size)
t.left(90)
t.forward(2 * size)
t.left(90)
t.forward(1 * size)
t.left(90)
t.forward(2 * size)
t.end_fill()

# 바퀴
t.up()
t.goto(-1.3 * size, -0.5 * size)
t.down()
t.color("black")
t.begin_fill()
t.circle(size_c)
t.end_fill()

t.up()
t.goto(1.3 * size, -0.5 * size)
t.down()
t.color("black")
t.begin_fill()
t.circle(size_c)
t.end_fill()
